### ISSUE TITLE
selecting commits does not link to GitHub

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/benchmarks#1]
When clicking a commit hash in the interface, eg 3cb61d67 in https://www.mdanalysis.org/benchmarks/#traj_reader.TrajReaderIteration.time_strides I get a link https://www.mdanalysis.org/benchmarks/#3cb61d67 that shows an empty asv frame.

For astropy in eg http://www.astropy.org/astropy-benchmarks/#io_ascii.time_ascii.CsvInt.time_write clicking on a commit 10da37d2  opens https://github.com/astropy/astropy/commit/10da37d2

Any idea what I should do? The asv.json is in the repo https://github.com/MDAnalysis/benchmarks/blob/master/asv.conf.json . I also tried 
```json
"repo": "https://github.com/MDAnalysis/mdanalysis.git"
```
without change in behavior.

@tylerjereddy any ideas?

**Comment by tylerjereddy** [comment]
I've not looked at this in detail, but have made a note on my calendar to look next week.
