### ISSUE TITLE
Bump up environment to py3.11

### ISSUE THREAD

**Issue by IAlibay** [MDAnalysis/benchmarks#13]
As per https://github.com/MDAnalysis/mdanalysis/issues/3878#issuecomment-1294274296

As far as I'm aware the environment for the benchmarks is done using conda. If that's the case, this will need to wait until the relevant upstream packages release py3.11 compatible versions first.

**Comment by orbeckst** [comment]
Thanks for raising the issue!

Yes, asv uses conda. Any idea by when 3.11 will install without issues?

**Comment by IAlibay** [comment]
For a full MDAnalysis install? Probably ~ couple of months, scipy has already released py311 stuff on conda-forge, but numpy hasn't, so everyone else might take some time.

I'm trying to set up some anacron jobs that will just send out reminders when things finally work.

**Comment by orbeckst** [comment]
I'm happy to change the env files and check that they work. I'll just need a reminder when we have the capability.

**Comment by IAlibay** [comment]
> I'm happy to change the env files and check that they work. I'll just need a reminder when we have the capability.

I've added it at the end of the "list of to-dos", as soon as we complete the "get this to work with github actions on core", that should give us a suitable reminder that this is next on the to-do list.

CF has been quite aggressively pushing for 3.11, so we might get there faster than we expect, I'll have a quick look through now. h5py says ~ 2 weeks until the next release.

**Comment by IAlibay** [comment]
@orbeckst good news, a minimal conda build works! https://github.com/MDAnalysis/mdanalysis/actions/runs/3396812665/jobs/5648295156

That being said, this will only work with 2.4.0-dev0, how do you go about setting this properly? https://github.com/MDAnalysis/benchmarks/blob/8ce0a0ea54e4540f751a99b8aa1c236ed4286aaf/scripts/cron.sh#L74

**Comment by orbeckst** [comment]
We'll need to replace 'release-1.0.1' with a tag or commit SHA1 that points to the commit that enables python 3.11 with MDA. 

In order to have an initial speed comparison I would like to have some parallel history with 3.8 and 3.11, so I wouldn't mind staying at 3.8 until post 2.4.0 and then switching. ASV will rerun the missing commits in 3.11. Essentially, I am justifying my laziness to not jump to a change right this moment ;-).

**Comment by IAlibay** [comment]
> We'll need to replace 'release-1.0.1' with a tag or commit SHA1 that points to the commit that enables python 3.11 with MDA.
> 
> In order to have an initial speed comparison I would like to have some parallel history with 3.8 and 3.11, so I wouldn't mind staying at 3.8 until post 2.4.0 and then switching. ASV will rerun the missing commits in 3.11. Essentially, I am justifying my laziness to not jump to a change right this moment ;-).

Ok that sounds reasonable, I'll move this to the 2.4.0 release tasks?

**Comment by orbeckst** [comment]
ok

**Comment by IAlibay** [comment]
Closing as completed.
