### ISSUE TITLE
include benchmarks from multiple machines

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/benchmarks#3]
We can add benchmarks from other machines to the repo and display them.

**Comment by orbeckst** [comment]
@tylerjereddy if you want to upload some of your benchmarks to the repo then we should be able to also display them. `asv publish` should take care of the formatting and sorting into different machines.

**Comment by tylerjereddy** [comment]
Ok, will do. Sadly I purged many of the older ones because I tend to work in a single repo and `git clean` etc. to keep working projects clean.

**Comment by orbeckst** [comment]
I merged and `asv publish` the combined results and we now have data from c3potato and gp160 at https://www.mdanalysis.org/benchmarks/#/summarylist

**Comment by orbeckst** [comment]
My conclusion is that this works exactly the way we imagined: just merge your results into the repo and it will show up as expected.
