### ISSUE TITLE
adding tests wiped out old related test data

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/benchmarks#8]
With the added GRO benchmarks PR MDAnalysis/mdanalysis#1968, suddenly all the old GRO data is gone: https://www.mdanalysis.org/benchmarks/#GRO.GROReadBench.time_create_GRO_universe

Perhaps (??) related to #7 or is it because MDAnalysis/mdanalysis#1968 removed the test `time_read_GRO_file`? But then the automation #2 *should* have rerun all older commits.

**Comment by richardjgowers** [comment]
Yeah so one benchmark was renamed, so it makes sense that the old data was purged (as no real way of knowing that it was renamed).  I'm surprised that the new benchmarks weren't rerun from 0.11 (or whenever our day 0 is)

**Comment by orbeckst** [comment]
Yes, the way I would have wanted it to work, new benchmarks should have been re-run from the beginning. Need to check.
